---
#net.ipv4.ip_nonlocal_bind sysctl to 1
#11. Well-known traps to avoid
#https://docs.haproxy.org/2.7/management.html#11
# tasks file for haproxy
  - name: Install keepalived
    ansible.builtin.apt:
      update_cache: yes
      name: keepalived
      state: present

  - name: Ensure group keepalived exists
    ansible.builtin.group:
      name: keepalived
      state: present

  - name: create keepalived user account
    ansible.builtin.user:
      name: keepalived
      groups: keepalived
      shell: /sbin/nologin
      append: true
      create_home: false
      state: present

  - name: Template keepalived.conf
    ansible.builtin.template:
      src: keepalived.conf.j2
      dest: /etc/keepalived/keepalived.conf
      owner: keepalived
      group: keepalived

#source: https://github.com/Oefenweb/ansible-keepalived
#
  - block:
    - name: allow binding non-local IPv4
      ansible.posix.sysctl:
        name: net.ipv4.ip_nonlocal_bind
        value: "{{ keepalived_ip_nonlocal_bind | string }}"
        reload: true
        state: present
      when: keepalived_ip_nonlocal_bind | bool

    - name: check if IPv6 is enabled
      ansible.builtin.slurp:
        src: /sys/module/ipv6/parameters/disable
      register: _ipv6_disabled

    - name: set ipv6_enabled fact
      ansible.builtin.set_fact:
        is_ipv6_enabled: "{{ not _ipv6_disabled.failed and '0' in (_ipv6_disabled.content | b64decode) }}"

    - name: allow binding non-local IPv6
      ansible.posix.sysctl:
        name: net.ipv6.ip_nonlocal_bind
        value: "{{ keepalived_ip_nonlocal_bind | string }}"
        reload: true
        state: present
      when:
        - keepalived_ip_nonlocal_bind | bool
        - is_ipv6_enabled
        