#ansible-playbook -i "inventory," node.yml -u root
---
- hosts: "*"
  become: true
  roles:
    - role: haproxy
      haproxy_bootnode_wss_external_port: "30633"
      haproxy_bootnode_wss_internal_port: "30533"
      haproxy_bootnode_rpc_internal_port: "9933"
      haproxy_prometheus_metrics_port: "8405"
      bootnodes_config:
        nodes:
          - external_hostname: "paseo.bootnode.stkd.io"
            ipAdress: "192.168.270.1"
          - external_hostname: "westend.bootnode.stkd.io"
            ipAdress: "192.168.270.2"
          - external_hostname: "kusama.bootnode.stkd.io"
            ipAdress: "192.168.270.3"
          - external_hostname: "polkadot.bootnode.stkd.io"
            ipAdress: "192.168.270.4"
      haproxy_wss_rpc_port: "443"
      rpc_config:
        chains:
          - name: polkadot
            nodes:
              - external_hostname: "polkadot.bootnode.stkd.io"
                ipAdress: "192.168.270.4"
              - external_hostname: "polkadot.rpc.stkd.io"
                ipAdress: "192.168.270.5"
          - name: kusama
            nodes:
              - external_hostname: "kusama.bootnode.stkd.io"
                ipAdress: "192.168.270.6"
              - external_hostname: "kusama.rpc.stkd.io"
                ipAdress: "192.168.270.7"
          - name: paseo
            nodes:
              - external_hostname: "paseo.bootnode.stkd.io"
                ipAdress: "192.168.270.8"
              - external_hostname: "paseo.rpc.stkd.io"
                ipAdress: "192.168.270.9"
          - name: westend
            nodes:
              - external_hostname: "westend.bootnode.stkd.io"
                ipAdress: "192.168.270.10"
              - external_hostname: "westend.rpc.stkd.io"
                ipAdress: "192.168.270.11"
