#ansible-playbook -i "inventory.ini," node.yml -u root
---
  - hosts: "*"
    become: true
    roles:
      - role: roles/ibp-nodes
        node_name: "stkd-us-ksm-bp-01"
        chain_name: "kusama"
        libp2p_port: "30333"
        rpc_port: "30433"
        ws_port: "30533"
        wss_port: "30633"
        prometheus_port: "9613"
        node_role: "boot"
        acme_email: ""
        warp: true
        node_fqdn: "us-ksm-01.bootnodes.stkd.io"
        
      # - role: roles/ibp-nodes
      #   node_name: "stkd-us-ksm-rp-01"
      #   chain_name: "kusama"
      #   rpc_port: "9936"
      #   libp2p_port: "30336"
      #   libp2p_ws_port: "30337"
      #   prometheus_port: "9616"
      #   node_role: "rpc"
      #   node_p2p_bind_dns: "us-ksm-01.rpc.stkd.io"
